### ISSUE TITLE
 Incorrect API key provided: your-ope*******-key.

### ISSUE THREAD

**Issue by jakenuts** [rokstrnisa/Robo-GPT#1]
I'm new to Python and pipenv but no matter what I do the script can't seem to see the .env file with my api keys. Renamed the .env.template file to .env, eventually tried copying it to the environment folder that was created, no luck. 

Thanks!

James

**Comment by rokstrnisa** [comment]
Hi James, what's the error you see?

**Comment by jakenuts** [comment]
Sorry, realized it's 99.9% likely to be a local environment thing, thanks!
