### ISSUE TITLE
No googlesearch module

### ISSUE THREAD

**Issue by koltregaskes** [rokstrnisa/Robo-GPT#3]
I've followed the instructions from the readme, run main.py and get the following error:

\Robo-GPT\robo-gpt\action_runner.py", line 9, in <module>
    from googlesearch import search
ModuleNotFoundError: No module named 'googlesearch'

What have I missed?

**Comment by rokstrnisa** [comment]
The most likely reason is that you either didn't create the pipenv shell (`pipenv shell`) or didn't install the pipenv dependencies (`pipenv install`) before trying to run the program (`python robo-gpt/main.py`).
